-- Below code is for snow to create DB, Schemas and commands which I used or practice to build this project
CREATE OR REPLACE DATABASE CAMPAIGN_ADS_DB;
CREATE OR REPLACE SCHEMA CAMPAIGN_ADS_DB.RAW;

CREATE OR REPLACE FILE FORMAT CAMPAIGN_ADS_DB.RAW.CSV_FORMAT
TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER = 1
NULL_IF =('','NULL','null') EMPTY_FIELD_AS_NULL = TRUE;

SELECT COUNT(*) FROM CAMPAIGN_ADS_DB.RAW.AD_ACCOUNTS;

CREATE SCHEMA IF NOT EXISTS CAMPAIGN_ADS_DB.ANALYTICS;

SELECT CURRENT_ACCOUNT_NAME();
SELECT CURRENT_ORGANIZATION_NAME();

SELECT CURRENT_USER();
SELECT CURRENT_ROLE();
SELECT CURRENT_WAREHOUSE();

SELECT * FROM AD_ACCOUNTS;


SELECT * FROM CAMPAIGN_ADS_DB.RAW.AD_PERFORMANCE;

SELECT
    date,
    ad_id,
    country,
    device,
    COUNT(*) AS record_count
FROM CAMPAIGN_ADS_DB.RAW.AD_PERFORMANCE
GROUP BY date,
    ad_id,
    country,
    device
HAVING COUNT(*) > 1
ORDER BY record_count;

SELECT * FROM CAMPAIGN_ADS_DB.RAW.AD_PERFORMANCE
WHERE AD_ID=10018 AND COUNTRY='IN' AND DEVICE='mobile'AND DATE='2025-05-06';

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_PERFORMANCE;


DESCRIBE TABLE CAMPAIGN_ADS_DB.RAW.AD_PERFORMANCE;


SELECT
    device,
    COUNT(*) AS row_count
FROM ANALYTICS.stg_ad_performance
GROUP BY device
ORDER BY row_count DESC;

SELECT *
FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_PERFORMANCE
WHERE spend < 0;


SELECT *
FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_PERFORMANCE
WHERE clicks > impressions;

SELECT *
FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_PERFORMANCE
WHERE conversions > clicks;

SELECT *
FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_PERFORMANCE
WHERE IMPRESSIONS=0
AND clicks > 0;

SELECT * FROM CAMPAIGN_ADS_DB.RAW.LEADS;

SELECT
lead_id,
COUNT(*) AS record_count
FROM CAMPAIGN_ADS_DB.RAW.LEADS
GROUP BY lead_id
HAVING COUNT(*) > 1;

SELECT
lead_id
FROM CAMPAIGN_ADS_DB.RAW.LEADS
WHERE lead_id = NULL;

SELECT DISTINCT lead_status
FROM CAMPAIGN_ADS_DB.RAW.LEADS;

SELECT DISTINCT LEAD_SOURCE
FROM CAMPAIGN_ADS_DB.RAW.LEADS;

SELECT
    l.campaign_id,
    l.ad_id
FROM CAMPAIGN_ADS_DB.RAW.LEADS l
LEFT JOIN CAMPAIGN_ADS_DB.RAW.CAMPAIGNS c
    ON l.campaign_id = c.campaign_id
LEFT JOIN CAMPAIGN_ADS_DB.RAW.AD_GROUPS ag
    ON c.campaign_id = ag.campaign_id
LEFT JOIN CAMPAIGN_ADS_DB.RAW.ADS a
    ON ag.ad_group_id = a.ad_group_id
    AND l.ad_id = a.ad_id
WHERE c.campaign_id IS NULL
   OR a.ad_id IS NULL;

SELECT
    l.lead_id,
    l.campaign_id AS lead_campaign_id,
    l.ad_id,
    ag.campaign_id AS ad_campaign_id

FROM CAMPAIGN_ADS_DB.RAW.LEADS l

LEFT JOIN CAMPAIGN_ADS_DB.RAW.ADS a
    ON l.ad_id = a.ad_id

LEFT JOIN CAMPAIGN_ADS_DB.RAW.AD_GROUPS ag
    ON a.ad_group_id = ag.ad_group_id

WHERE l.campaign_id != ag.campaign_id;

SELECT
    LOWER(vehicle_type) AS vehicle_type,
    COUNT(*) AS row_count
FROM CAMPAIGN_ADS_DB.RAW.LEADS
GROUP BY LOWER(vehicle_type)
ORDER BY vehicle_type;

SELECT
    vehicle_type,
    COUNT(*) AS row_count
FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_LEADS
GROUP BY vehicle_type
ORDER BY vehicle_type;

SELECT conversion_id, COUNT(*) FROM CAMPAIGN_ADS_DB.RAW.CONVERSIONS GROUP BY conversion_id having COUNT(*) > 1;

DESCRIBE TABLE CAMPAIGN_ADS_DB.RAW.CONVERSIONS;

SELECT * FROM CAMPAIGN_ADS_DB.RAW.AD_ACCOUNTS;
SELECT * FROM CAMPAIGN_ADS_DB.RAW.AD_GROUPS;
SELECT * FROM CAMPAIGN_ADS_DB.RAW.ADS;
SELECT * FROM CAMPAIGN_ADS_DB.RAW.CAMPAIGNS;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.INT_AD_HIERARCHY;

SELECT
    ad_id,
    COUNT(*) as record_count
FROM CAMPAIGN_ADS_DB.ANALYTICS.INT_AD_HIERARCHY
GROUP BY ad_id
HAVING COUNT(*) > 1;


SELECT * FROM leads;
SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.INT_AD_HIERARCHY;


SELECT 
-- lead table
l.lead_id,
l.customer_id,
l.lead_status,
l.lead_value,
l.vehicle_type,
l.vehicle_category,
l.created_at,
-- ad_hierarchy table
h.ad_id,
h.ad_name,
h.ad_group_id,
h.ad_group_name,
h.campaign_id,
h.campaign_name,
h.objective,
h.account_id,
h.account_name,
h.platform
FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_LEADS l
LEFT JOIN CAMPAIGN_ADS_DB.ANALYTICS.INT_AD_HIERARCHY h 
ON l.ad_id = h.ad_id;   

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.INT_LEAD_FUNNEL;

SELECT 
lead_id,
COUNT(*) AS record_count
FROM CAMPAIGN_ADS_DB.ANALYTICS.INT_LEAD_FUNNEL
GROUP BY lead_id
HAVING COUNT(*) > 1;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_CONVERSIONS;   

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.INT_CONVERSION_DETAILS;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_CAMPAIGNS;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_GROUPS;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.DIM_CAMPAIGNS;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.STG_AD_PERFORMANCE;
SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.FCT_ADS_PERFORMANCE WHERE COUNTRY IS NULL;
SELECT
    country,
    COUNT(*)
FROM CAMPAIGN_ADS_DB.RAW.AD_PERFORMANCE
GROUP BY country;
SELECT
    date,
    ad_id,
    COUNT(*)
FROM CAMPAIGN_ADS_DB.ANALYTICS.FCT_ADS_PERFORMANCE
GROUP BY
    date,
    ad_id
HAVING COUNT(*) > 1;

SELECT * FROM CAMPAIGN_ADS_DB.RAW.CAMPAIGNS;
DESC TABLE ANALYTICS.FCT_ADS_PERFORMANCE;
DESC TABLE ANALYTICS.FCT_CONVERSION;

UPDATE RAW.CAMPAIGNS
SET
    DAILY_BUDGET = 3000,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE CAMPAIGN_ID = '1005';

SELECT
    campaign_id,
    daily_budget,
    dbt_valid_from,
    dbt_valid_to
FROM SNAPSHOTS.CAMPAIGNS_SNAPSHOT
ORDER BY campaign_id, dbt_valid_from;

SELECT * FROM CAMPAIGN_ADS_DB.ANALYTICS.DIM_CAMPAIGNS;

SELECT *, ROW_NUMBER() OVER(ORDER BY REVENUE DESC) AS rn FROM CAMPAIGN_ADS_DB.ANALYTICS.RPT_EXECUTIVE_DASHBOARD;

CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE TABLE IF NOT EXISTS AUDIT.MODEL_RUN_LOG (
    RUN_ID STRING,
    MODEL_NAME STRING,
    RUN_TIME TIMESTAMP,
    
    STATUS STRING
    
);

SELECT * FROM CAMPAIGN_ADS_DB.AUDIT.MODEL_RUN_LOG;